export const ERROR_CODE = {
  UNAUTHORIZED: "UNAUTHORIZED",
  UNAUTHENTICATED: "UNAUTHENTICATED",
};

export enum PROCESS_STATUS {
  PENDING = "PENDING",
  PROCESSED = "PROCESSED",
  FINISHED = "FINISHED",
}

export const REDUCED_PRICE_MAP: Record<string, string[]> = {
  "12a20100-4464-49cd-9e27-d19a9d0730e0": [
    "Phường Việt Trì",
    "Phường Nông Trang",
    "Phường Thanh Miếu",
    "Phường Vân Phú",
    "Xã Hy Cương",
  ],
  "ad9eea86-2dcf-4478-ae36-dceb0cfedb7d": [
    "Phường Vĩnh Phúc",
    "Phường Vĩnh Yên",
  ],
  "ae5ba99b-010e-4ff6-8da5-ece24da22193": [
    "Phường Hoà Bình",
    "Phường Kỳ Sơn",
    "Phường Tân Hoà",
    "Phường Thống Nhất",
    "Xã Thịnh Minh",
  ],
};

export const dangerousDestinationList = [
  {
    destinations: [
      "Cao Sơn",
      "Đức Nhàn",
      "Quy Đức",
      "Tân Pheo",
      "Mai Châu",
      "Bao La",
      "Pà Cò",
      "Tân Mai",
    ],
    fee: 50000,
  },
  {
    destinations: [
      "Đà Bắc",
      "Tiền Phong",
      "Ngọc Sơn",
      "Mai Hạ",
      "Vân Sơn",
      "Khả Cửu",
    ],
    fee: 45000,
  },
  {
    destinations: [
      "Thượng Long",
      "Sơn Lương",
      "Xuân Viên",
      "Trung Sơn",
      "Tân Sơn",
      "Xuân Đài",
      "Long Cốc",
      "Cao Phong",
      "Mường Thàng",
      "Thung Nai",
      "Mường Động",
      "Dũng Tiến",
      "Nật Sơn",
      "Mường Vang",
      "Nhân Nghĩa",
      "Quyết Thắng",
      "Thượng Cốc",
      "Yên Phú",
      "An Bình",
      "Mường Hoa",
      "Toàn Thắng",
      "Lạc Dương",
      "Đạo Trù",
      "Văn Miếu",
      "Lai Đồng",
      "Tam Đảo",
    ],
    fee: 40000,
  },
  {
    destinations: [
      "Yên Lập",
      "Minh Hòa",
      "Hùng Việt",
      "Đồng Lương",
      "Võ Miếu",
      "Cự Đồng",
      "Hương Cần",
      "Yên Sơn",
      "Minh Đài",
      "Thu Cúc",
      "Yên Lãng",
      "Kim Bôi",
      "Hợp Kim",
      "Lạc Sơn",
      "Đại Đồng",
      "Lạc Thuỷ",
      "An Nghĩa",
      "Lương Sơn",
      "Cao Dương",
      "Liên Sơn",
      "Tân Lạc",
      "Mường Bi",
      "Yên Trị",
      "Thịnh Minh",
      "Kỳ Sơn",
      "Tân Hòa",
      "Thanh Sơn",
      "Đại Đình",
    ],
    fee: 35000,
  },
  {
    destinations: [
      "Hạ Hòa",
      "Đan Thượng",
      "Yên Kỳ",
      "Vĩnh Chân",
      "Văn Lang",
      "Hiền Lương",
      "Đoan Hùng",
      "Tây Cốc",
      "Chân Mộng",
      "Chí Đám",
      "Bằng Luân",
      "Thanh Ba",
      "Quảng Yên",
      "Hoàng Cương",
      "Đông Thành",
      "Chí Tiên",
      "Phù Ninh",
      "Dân Chủ",
      "Phú Mỹ",
      "Trạm Thản",
      "Bình Phú",
      "Cẩm Khê",
      "Phú Khê",
      "Tiên Lương",
      "Vân Bán",
      "Tam Nông",
      "Thọ Văn",
      "Vạn Xuân",
      "Hiền Quan",
      "Xuân Lũng",
      "Thanh Thuỷ",
      "Đào Xá",
      "Tu Vũ",
      "Hy Cương",
      "Bình Tuyền",
      "Hợp Lý",
      "Yên Thuỷ",
      "Tam Dương Bắc",
      "Hải Lựu",
      "Tam Sơn",
      "Lập Thạch",
      "Thái Hòa",
      "Liên Hà",
    ],
    fee: 30000,
  },
];
