export const ERROR_CODE = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
}

export enum PROCESS_STATUS {
    PENDING =  "PENDING",
    PROCESSED = "PROCESSED",
    FINISHED = "FINISHED" 
}